questions = [
    {"question": "Sharks have been around longer than trees.", "answer": "True"},
    {"question": "All sharks must keep moving to stay alive.", "answer": "False"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "Great white sharks can live up to 70 years.", "answer": "True"},
    {"question": "Sharks can only be found in saltwater.", "answer": "False"},
    {"question": "Sharks have no bones in their bodies.", "answer": "True"},
    {"question": "Sharks have good eyesight.", "answer": "True"},
    {"question": "Sharks can be found in every ocean in the world.", "answer": "True"},
    {"question": "All sharks are dangerous to humans.", "answer": "False"},
    {"question": "Sharks can smell blood from miles away.", "answer": "True"},
    {"question": "Sharks do not get cancer.", "answer": "False"},
    {"question": "Sharks lay eggs.", "answer": "True"},
    {"question": "Sharks have a sixth sense to detect electromagnetic fields.", "answer": "True"},
    {"question": "Most sharks are cold-blooded.", "answer": "True"},
    {"question": "Sharks have been on Earth for about 400 million years.", "answer": "True"},
    {"question": "Sharks can swim backwards.", "answer": "False"},
    {"question": "Sharks have multiple rows of teeth.", "answer": "True"},
    {"question": "A group of sharks is called a school.", "answer": "False"},
    {"question": "The largest shark species is the whale shark.", "answer": "True"},
    {"question": "Sharks can replace their teeth throughout their lives.", "answer": "True"},
    {"question": "Hammerhead sharks have a 360-degree view due to their head shape.", "answer": "True"},
    {"question": "Sharks are immune to all diseases.", "answer": "False"},
    {"question": "Sharks do not have scales like other fish.", "answer": "True"},
    {"question": "Sharks can live in freshwater.", "answer": "True"},
    {"question": "Sharks have been known to migrate thousands of miles.", "answer": "True"},
]
